Refactored ReCaptcha logic
dotkernel/frontend pull request #291
Opened 2022-08-26 15:11 UTC by MarioRadu

2022-08-26 16:43 UTC, alexmerlin requested changes

2022-08-26 16:43 UTC, alexmerlin commented on composer.json
> +        "roave/psr-container-doctrine": "^3.5.0",
This is not a valid JSON - you need to remove the trailing comma.

2022-08-26 16:43 UTC, alexmerlin commented on src/App/src/Service/RecaptchaService.php
> +    public function setScoreThreshold(float $scoreThreshold): self
Correct me if I'm wrong, but I don't think that one would set this value at runtime (like form1 has the threshold set to .5 while form2 has a different value) - so, I guess accessing the value from the config would suffice. If so, this class does not need the `scoreThreshold` property and can read it directly from the config when it needs to.

2022-08-26 16:43 UTC, alexmerlin commented on src/App/src/Service/RecaptchaService.php
> +        $this->scoreThreshold = $config['scoreThreshold'];
I think we should validate the mandatory config fields (`siteKey`, `secretKey` and `verifyUrl`) and throw an exception if any of them is missing. Maybe if you switch to reading `scoreThreshold` from `$this->config`, that could have a default value (of `0.5`).

2022-08-26 16:43 UTC, alexmerlin commented on src/App/src/Service/RecaptchaService.php
> +        if ($statusCode !== StatusCodeInterface::STATUS_OK) {
Not as clean as with Guzzle... but, it's the best we can do without, right? :)

2022-08-26 16:43 UTC, alexmerlin commented on src/Contact/src/Controller/ContactController.php
>                      $this->messenger->addError('Wrong recaptcha');
Would change this message to something more understandable for the user:

> Captcha verification failed. Please try again.

2022-08-26 18:58 UTC, MarioRadu commented on src/App/src/Service/RecaptchaService.php
> +    public function setScoreThreshold(float $scoreThreshold): self
Calling `setScoreThreshold` can change the value of `scoreThreshold` at runtime. If you have multiple instances of the same class (RecaptchaService) instantiated you can have multiple score thresholds. This method just overwrites the value from the config file, if needed at runtime.

For example: 
You could have a class that has `RecaptchaService` class as a dependency, with the default `scoreThreshold` of 0.5.
You want to create a custom form that needs a `scoreThreshold` of > 0.7 for example, you can achieve this using the `setScoreThreshold` method.

`$this->recaptchaService->setScoreThreshold(0.7)->setResponse('test')->isValid();`

2022-08-26 19:02 UTC, MarioRadu commented on src/App/src/Service/RecaptchaService.php
> +        $this->scoreThreshold = $config['scoreThreshold'];
Yes, you are right.

2022-08-26 20:04 UTC, MarioRadu commented on src/App/src/Service/RecaptchaService.php
> +        if ($statusCode !== StatusCodeInterface::STATUS_OK) {
We will never know.

2022-08-26 20:58 UTC, MarioRadu commented on src/Contact/src/Controller/ContactController.php
>                      $this->messenger->addError('Wrong recaptcha');
Sounds good.

2022-08-30 08:01 UTC, alexmerlin commented on src/App/src/Service/RecaptchaService.php
> +            if ($key === 'scoreThreshold' && ! is_float($config[$key])) {
This condition could be moved after the foreach so we don't check with each iteration if it's the `scoreThreshold` we're looking at. If you make the previous suggestion, you can use the key's name in the thrown exception message:

```
throw new InvalidArgumentException(
    'Invalid scoreThreshold provided. The value must be a float between 0 and 1.'
);
```

If the message claims that `scoreThreshold` must be between 0 and 1, this should also be verified in the condition.
```
foreach ($keysToValidate as $key) {
    if (empty($config[$key])) {
        throw new InvalidArgumentException("Invalid `{$key}` provided.");
    }
}

if (! is_float($config['scoreThreshold']) || $config['scoreThreshold'] < 0 || $config['scoreThreshold'] > 1) {
    throw new InvalidArgumentException(
        "Invalid `{$key}` provided. The value must be a float between 0.0 and 1.0"
    );
}
```

**Note:** 
If someone enters `scoreThreshold` as an integer (_1_ instead of _1.0_ or _0_ instead of _0.0_), the above condition will fail because `is_float(0)` and `is_float(1)` return **false**. Casting scoreThreshold to float in local.php.dist could be an easy fix for this:
```
...
'recaptcha' => [
        'scoreThreshold' => (float) 0.5,
        ...
```

2022-08-30 09:18 UTC, arhimede approved these changes
I would prefered to use Guzzle too, but

2022-08-30 09:21 UTC, merged