Replaced annotations with attributes
dotkernel/frontend pull request #446
Opened 2024-07-23 07:54 UTC by MarioRadu

2024-07-23 09:00 UTC, alexmerlin requested changes

2024-07-23 09:00 UTC, alexmerlin commented on src/User/src/ConfigProvider.php
> +                UserRoleRepository::class    => AttributedRepositoryFactory::class,
Error on login:
> Unable to resolve service "Frontend\User\EventListener\UserAvatarEventListener" to a factory; are you certain you provided it during configuration?

```suggestion
                UserRoleRepository::class         => AttributedRepositoryFactory::class,
                UserAvatarEventListener::class => AttributedServiceFactory::class,
```

Also, don't forget to add `use Frontend\User\EventListener\UserAvatarEventListener;`.

2024-07-23 09:00 UTC, alexmerlin commented on .laminas-ci/pre-run.sh
> +fi
```suggestion
fi

```

2024-07-23 09:00 UTC, alexmerlin commented on README.md
>  [![Build Static](https://github.com/dotkernel/frontend/actions/workflows/static-analysis.yml/badge.svg?branch=4.0)](https://github.com/dotkernel/frontend/actions/workflows/static-analysis.yml)
```suggestion
[![Build Static](https://github.com/dotkernel/frontend/actions/workflows/continuous-integration.yml/badge.svg?branch=4.0)](https://github.com/dotkernel/frontend/actions/workflows/continuous-integration.yml)
```

2024-07-23 09:00 UTC, alexmerlin commented on README.md
>  [![Build Static](https://github.com/dotkernel/frontend/actions/workflows/run-tests.yml/badge.svg?branch=4.0)](https://github.com/dotkernel/frontend/actions/workflows/run-tests.yml)
```suggestion
```

2024-07-23 09:00 UTC, alexmerlin commented on README.md
Replace `bash` with `shell` in fenced code blocks, because bash is a specific type of shell - we have to use the generic term.

2024-07-23 09:00 UTC, alexmerlin commented on src/App/src/Common/Message.php
From what I see, the two new messages that you've added are not used anywhere.
Let's also check the rest of the messages if there are more unused ones.

2024-07-24 06:09 UTC, alexmerlin commented on src/App/src/Common/Message.php
Let's remove these unused messages:

- INVALID_VALUE
- MAIL_SENT_USER_ACTIVATION
- NOT_FOUND_BY_UUID
- RESET_PASSWORD_VALID
- RESOURCE_NOT_ALLOWED
- RESTRICTION_IMAGE
- USER_NOT_FOUND_BY_EMAIL
- VALIDATOR_REQUIRED_FIELD
- VALIDATOR_REQUIRED_UPLOAD

2024-07-24 06:10 UTC, alexmerlin commented on README.md
>  [![Build Static](https://github.com/dotkernel/frontend/actions/workflows/static-analysis.yml/badge.svg?branch=4.0)](https://github.com/dotkernel/frontend/actions/workflows/static-analysis.yml)
Also, replace `Build static` with `Continuous Integration` and `4.0` with `5.0`.

2024-07-24 06:18 UTC, alexmerlin approved these changes

2024-07-24 09:11 UTC, arhimede approved these changes

2024-07-24 09:11 UTC, merged