updated account delete
dotkernel/frontend pull request #480
Opened 2024-09-05 12:15 UTC by bidi47

2024-09-05 12:22 UTC, bidi47 commented
other changes
- moved some messages to the Message class (authentication)
- added the messages to the homepage - in this case, to confirm the account deletion

2024-09-06 04:43 UTC, alexmerlin requested changes

2024-09-06 04:43 UTC, alexmerlin commented on src/User/src/Service/UserService.php
> +                $user->setIdentity('anonymous' . date('dmYHis') . $this->config['userAnonymizeAppend']);
```suggestion
                $user->setIdentity(
                    sprintf('anonymous%s@%s', date('dmYHis'), $this->config['userAnonymizeAppend'])
                );
```
You had a missing `@` between the date and the configured append part.
Also, for better readability, I suggest using `sprintf`.

2024-09-06 04:43 UTC, alexmerlin commented on config/autoload/local.php.dist
> +    'userAnonymizeAppend' => '',
FYI, I created an issue in the frontend documentation repo, to document the user anonymization and this new config value.
https://github.com/dotkernel/frontend-documentation/issues/6

(not a blocker for this issue, just a thing for us to keep in mind)

2024-09-06 11:34 UTC, bidi47 commented on src/User/src/Service/UserService.php
> +                $user->setIdentity('anonymous' . date('dmYHis') . $this->config['userAnonymizeAppend']);
i just assumed the config (userAnonymizeAppend) would have the '@'
either way, your solution is better

2024-09-06 11:41 UTC, bidi47 commented on config/autoload/local.php.dist
> +    'userAnonymizeAppend' => '',
got it

2024-09-06 13:27 UTC, alexmerlin commented on src/User/src/Service/UserService.php
> +                $user->setIdentity('anonymous' . date('dmYHis') . $this->config['userAnonymizeAppend']);
When I tested locally, I forgot that @arhimede's [comment](https://github.com/dotkernel/frontend/issues/479#issuecomment-2331111238) included both the `@` symbol and the domain name.
I just set `userAnonymizeAppend` to `dotkernel.com` and after testing, I ended up with an anonymized email without the `@` in it.
Your solution was just as correct as mine, but IMHO the `sprintf` solution looks more readable than concatenating four strings.

2024-09-06 13:37 UTC, alexmerlin approved these changes

2024-09-10 09:29 UTC, merged