account delete - avatar
dotkernel/frontend pull request #483
Opened 2024-09-11 20:11 UTC by bidi47

2024-09-12 05:17 UTC, alexmerlin requested changes

2024-09-12 05:17 UTC, alexmerlin commented on src/User/src/Repository/UserAvatarRepository.php
> +    public function deleteAvatar(string $uuid): mixed
Replace method with:

```php
    public function deleteAvatar(UserAvatar $avatar): void
    {
        $this->getEntityManager()->remove($avatar);
        $this->getEntityManager()->flush();
    }
```

2024-09-12 05:17 UTC, alexmerlin commented on src/User/src/Repository/UserAvatarRepository.php
> +use Ramsey\Uuid\Uuid;
```suggestion
```

2024-09-12 05:17 UTC, alexmerlin commented on src/User/src/Service/UserService.php
> +    public function deleteAvatar(User $user): void
Replace method with:

```php
public function deleteAvatar(User $user): void
    {
        $avatar = $user->getAvatar();
        if (! $avatar instanceof UserAvatar) {
            return;
        }

        $path = sprintf('%s/%s/', $this->config['uploads']['user']['path'], $user->getUuid()->toString());
        $this->deleteAvatarFile($path . $avatar->getName());
        rmdir($path);

        $this->userAvatarRepository->deleteAvatar($avatar);
    }
```

Because, first we need to check if the user has an avatar using `$avatar instanceof UserAvatar`:
- if not: we return, because there is no avatar file or entity to be deleted
Without checking if the user has an avatar, when calling `$this->deleteAvatarFile($path . $avatar->getName());` the code would try to delete what is in the `$path` variable (`public/uploads/user/`) because `$avatar->getName()` would be empty.
- else, we proceed with the flow execution

Also introduced `rmdir($path);` in order to delete the user directory that is empty after deleting the avatar file.
Make sure you add `use function rmdir;` to the `use` section of UserService.

2024-09-12 09:35 UTC, bidi47 commented on src/User/src/Service/UserService.php
> +    public function deleteAvatar(User $user): void
makes sense. implemented in new push

2024-09-12 09:36 UTC, bidi47 commented on src/User/src/Repository/UserAvatarRepository.php
> +    public function deleteAvatar(string $uuid): mixed
replaced and tested

2024-09-12 11:51 UTC, alexmerlin approved these changes

2024-09-13 05:37 UTC, alexmerlin commented
@bidi47 Don't forget to link the PR with the issue it fixes.

2024-09-13 09:06 UTC, merged