Composer post install script to copy .dist files
dotkernel/frontend pull request #522
Opened 2024-12-02 09:52 UTC by MarioRadu

2024-12-02 10:29 UTC, alexmerlin commented on bin/composer-post-package-install-script.php
Is this file used anywhere?

2024-12-03 10:51 UTC, arhimede commented on composer.json
> +            "php -r \"if (is_readable('config/autoload/local.php')) { echo 'File already exists' . PHP_EOL; } else { copy('config/autoload/local.php.dist', 'config/autoload/local.php'); echo 'File co
Instead of `File copied successfully`
maybe something like 
`Mail config file created`
`Main config file created`
`Test config file created`

2024-12-04 07:29 UTC, alexmerlin requested changes

2024-12-04 07:29 UTC, alexmerlin commented on composer.lock
Not sure how you managed to add it, this file is in .gitignore - it should not be in the repo.

2024-12-04 07:29 UTC, alexmerlin commented on bin/composer-post-install-script.php
> +    [
```suggestion
    [
        'source'      => 'vendor/dotkernel/dot-mail/config/mail.global.php.dist',
        'destination' => 'config/autoload/mail.global.php.dist',
    ],
    [
```
`mail.global.php.dist` should also be copied - so it gets added to the repo.

2024-12-04 07:29 UTC, alexmerlin commented on bin/composer-post-install-script.php
> +        'source'      => 'vendor/dotkernel/dot-mail/config/mail.global.php.dist',
```suggestion
        'source'      => 'config/autoload/mail.global.php.dist',
```
`mail.global.php.dist` already created at the previous iteration, you can use that as the source file for this operation.

2024-12-04 07:59 UTC, MarioRadu commented on bin/composer-post-install-script.php
> +        'source'      => 'vendor/dotkernel/dot-mail/config/mail.global.php.dist',
I think it's better to keep the same source, because copying files could fail, and you have to make sure the files are copied in a specific order (.dist files first).

2024-12-04 08:04 UTC, MarioRadu commented on composer.lock
Previously we were using the `post-install-cmd` which only gets triggered after you run the `composer install` command, but there is a catch : the `composer.lock` file needs to be present and since we don't include the `composer.lock` file in git I had to switch to the `post-update-cmd` composer command which is triggered at an `composer install` or `composer update` event when there is no `composer.lock` file present.
I added the `composer.lock` file for testing purposes but I've removed it now.

2024-12-04 08:12 UTC, alexmerlin commented on bin/composer-post-install-script.php
> +        'source'      => 'vendor/dotkernel/dot-mail/config/mail.global.php.dist',
👍

2024-12-04 08:17 UTC, alexmerlin commented on bin/composer-post-install-script.php
> +    [
Actually we do not need the presence of a `.dist` version with `.global.php` config files - you can remove this branch of the array.
My bad!

2024-12-04 09:59 UTC, alexmerlin approved these changes

2024-12-11 10:50 UTC, closed without merging